search bar with search filter
UTACE/ACEKnow pull request #12
Opened 2021-07-11 01:46 UTC by CathyF9600

2021-07-11 01:51 UTC, RobertRen1122 commented
We removed the search button and added a filter. (with 5 links to different sites included)

2021-07-13 11:54 UTC, Louis-He requested changes

2021-07-13 11:54 UTC, Louis-He commented on frontend/package.json
> +    "@material-ui/core": "^4.12.1",
unnecessary dependency

2021-07-13 11:54 UTC, Louis-He commented on frontend/package.json
> +    "@material-ui/icons": "^4.11.2"
Please use the bootstrap icons instead. No mixed use of bootstrap and material

2021-07-18 18:46 UTC, RobertRen1122 commented
changes reviewed

2021-07-29 14:07 UTC, RobertRen1122 commented
Trying carousel, closing this branch

2021-07-29 14:07 UTC, closed without merging