Navbar
UTACE/ACEKnow pull request #17
Opened 2021-07-29 14:05 UTC by RobertRen1122

2021-07-31 12:08 UTC, Louis-He requested changes

2021-07-31 12:08 UTC, Louis-He commented on aceknow/settings.py
> +DEBUG = False
Leave it as true in development

2021-07-31 12:08 UTC, Louis-He commented on frontend/package-lock.json
> +    "@material-ui/core": {
Do we have to use material-ui?

2021-08-01 22:47 UTC, CatherineZM commented
Do we need this pull request? Isn't nav bar already in search bar page?

2021-08-01 22:50 UTC, RobertRen1122 commented
> Do we need this pull request? Isn't nav bar already in search bar page?

Search bar branch was checked out from nav bar branch, we can close this pr. Cathy or I could clean up the code on the search bar pr.

2021-08-01 22:52 UTC, CatherineZM commented
> > Do we need this pull request? Isn't nav bar already in search bar page?
> 
> Search bar branch was checked out from nav bar branch, we can close this pr. Cathy or I could clean up the code on the search bar pr.

@RobertRen1122 sounds good. I will close this pr and after you clean up the comments in search bar pr it's good to go.

2021-08-01 22:52 UTC, closed without merging