Search bar
UTACE/ACEKnow pull request #22
Opened 2021-08-01 03:17 UTC by CathyF9600

enlarged search bar with carousel background

2021-08-01 03:21 UTC, RobertRen1122 approved these changes
Looks nice :)

2021-08-01 22:38 UTC, CatherineZM commented
Looks good!

2021-08-01 22:41 UTC, CatherineZM requested changes

2021-08-01 22:41 UTC, CatherineZM commented on frontend/src/Components/HomePage/SearchBar.js
> +                 // autocomplete="off"
Clean up the comments

2021-08-01 22:41 UTC, CatherineZM commented on frontend/src/HomePage.js
> +// import Footer from "./Components/HomePage/Footer";
footer was commented out?

2021-08-01 22:41 UTC, CatherineZM commented on frontend/src/styles/BootstrapCarousel.css
> +  /*margin-top: 20vh;*/
Clean up comments as well

2021-08-01 22:41 UTC, CatherineZM commented on frontend/src/styles/SearchBar.css
> +/*    background-color: rgba(250, 247, 247, 0.75);*/
Same here

2021-08-03 12:49 UTC, CatherineZM approved these changes

2021-08-03 12:49 UTC, merged